/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface ClassPriceView {
  class_price: number;
  idx: number;
}

export interface DefineAward {
  awardEngName: string;
  awardHanName: string;
  idx: number;
  limitrankingPoint: number;
}

export interface DefineBlockIP {
  endDate: Generated<Date | null>;
  idx: Generated<number>;
  note: string | null;
  regDate: Generated<Date>;
  userID: string | null;
  userIP: string;
}

export interface DefineClass {
  classEngName: string;
  classHanName: string;
  idx: number;
  limitrankingLevel: Generated<number>;
  limituseLevel: Generated<number>;
  movieorderby: number;
  premiumType: Generated<number>;
}

export interface DefineClassPrice {
  class1_price: Generated<number>;
  class10_price: Generated<number>;
  class100_price: Generated<number>;
  class101_price: Generated<number>;
  class102_price: Generated<number>;
  class103_price: Generated<number>;
  class104_price: Generated<number>;
  class105_price: Generated<number>;
  class106_price: Generated<number>;
  class107_price: Generated<number>;
  class108_price: Generated<number>;
  class109_price: Generated<number>;
  class11_price: Generated<number>;
  class110_price: Generated<number>;
  class111_price: Generated<number>;
  class112_price: Generated<number>;
  class113_price: Generated<number>;
  class114_price: Generated<number>;
  class115_price: Generated<number>;
  class116_price: Generated<number>;
  class117_price: Generated<number>;
  class118_price: Generated<number>;
  class119_price: Generated<number>;
  class12_price: Generated<number>;
  class120_price: Generated<number>;
  class121_price: Generated<number>;
  class122_price: Generated<number>;
  class123_price: Generated<number>;
  class124_price: Generated<number>;
  class125_price: Generated<number>;
  class126_price: Generated<number>;
  class127_price: Generated<number>;
  class128_price: Generated<number>;
  class129_price: Generated<number>;
  class13_price: Generated<number>;
  class130_price: Generated<number>;
  class131_price: Generated<number>;
  class132_price: Generated<number>;
  class133_price: Generated<number>;
  class134_price: Generated<number>;
  class135_price: Generated<number>;
  class136_price: Generated<number>;
  class137_price: Generated<number>;
  class138_price: Generated<number>;
  class139_price: Generated<number>;
  class14_price: Generated<number>;
  class140_price: Generated<number>;
  class141_price: Generated<number>;
  class142_price: Generated<number>;
  class143_price: Generated<number>;
  class144_price: Generated<number>;
  class145_price: Generated<number>;
  class146_price: Generated<number>;
  class147_price: Generated<number>;
  class148_price: Generated<number>;
  class149_price: Generated<number>;
  class15_price: Generated<number>;
  class150_price: Generated<number>;
  class16_price: Generated<number>;
  class17_price: Generated<number>;
  class18_price: Generated<number>;
  class19_price: Generated<number>;
  class2_price: Generated<number>;
  class20_price: Generated<number>;
  class21_price: Generated<number>;
  class22_price: Generated<number>;
  class23_price: Generated<number>;
  class24_price: Generated<number>;
  class25_price: Generated<number>;
  class26_price: Generated<number>;
  class27_price: Generated<number>;
  class28_price: Generated<number>;
  class29_price: Generated<number>;
  class3_price: Generated<number>;
  class30_price: Generated<number>;
  class31_price: Generated<number>;
  class32_price: Generated<number>;
  class33_price: Generated<number>;
  class34_price: Generated<number>;
  class35_price: Generated<number>;
  class36_price: Generated<number>;
  class37_price: Generated<number>;
  class38_price: Generated<number>;
  class39_price: Generated<number>;
  class4_price: Generated<number>;
  class40_price: Generated<number>;
  class41_price: Generated<number>;
  class42_price: Generated<number>;
  class43_price: Generated<number>;
  class44_price: Generated<number>;
  class45_price: Generated<number>;
  class46_price: Generated<number>;
  class47_price: Generated<number>;
  class48_price: Generated<number>;
  class49_price: Generated<number>;
  class5_price: Generated<number>;
  class50_price: Generated<number>;
  class51_price: Generated<number>;
  class52_price: Generated<number>;
  class53_price: Generated<number>;
  class54_price: Generated<number>;
  class55_price: Generated<number>;
  class56_price: Generated<number>;
  class57_price: Generated<number>;
  class58_price: Generated<number>;
  class59_price: Generated<number>;
  class6_price: Generated<number>;
  class60_price: Generated<number>;
  class61_price: Generated<number>;
  class62_price: Generated<number>;
  class63_price: Generated<number>;
  class64_price: Generated<number>;
  class65_price: Generated<number>;
  class66_price: Generated<number>;
  class67_price: Generated<number>;
  class68_price: Generated<number>;
  class69_price: Generated<number>;
  class7_price: Generated<number>;
  class70_price: Generated<number>;
  class71_price: Generated<number>;
  class72_price: Generated<number>;
  class73_price: Generated<number>;
  class74_price: Generated<number>;
  class75_price: Generated<number>;
  class76_price: Generated<number>;
  class77_price: Generated<number>;
  class78_price: Generated<number>;
  class79_price: Generated<number>;
  class8_price: Generated<number>;
  class80_price: Generated<number>;
  class81_price: Generated<number>;
  class82_price: Generated<number>;
  class83_price: Generated<number>;
  class84_price: Generated<number>;
  class85_price: Generated<number>;
  class86_price: Generated<number>;
  class87_price: Generated<number>;
  class88_price: Generated<number>;
  class89_price: Generated<number>;
  class9_price: Generated<number>;
  class90_price: Generated<number>;
  class91_price: Generated<number>;
  class92_price: Generated<number>;
  class93_price: Generated<number>;
  class94_price: Generated<number>;
  class95_price: Generated<number>;
  class96_price: Generated<number>;
  class97_price: Generated<number>;
  class98_price: Generated<number>;
  class99_price: Generated<number>;
  idx: Generated<number>;
  regDate: Generated<Date>;
}

export interface DefineConfig {
  idx: Generated<number>;
  note: string | null;
  objName: string;
  regDate: Generated<Date>;
  value1: string;
  value2: string | null;
  value3: string | null;
  value4: string | null;
  value5: string | null;
}

export interface DefineEncodeKey {
  encodeKey: string;
  idx: Generated<number>;
  regDate: Generated<Date>;
}

export interface DefineGameServer {
  clientPort: number;
  connNumber: Generated<number>;
  idx: Generated<number>;
  regDate: Generated<Date>;
  serverID: Generated<number>;
  serverIP: string;
  serverName: string | null;
  serverPort: number;
  status: Generated<number>;
}

export interface DefineGearCustomidx {
  accountIDX: Generated<number>;
  idx: Generated<number>;
}

export interface DefineGeoip {
  country: string;
  countryname: string;
  ebwv: number;
  eip: string;
  sbwv: number;
  sip: string;
}

export interface DefineHeroPrice {
  HeroCode: Generated<number>;
  HeroPrice: Generated<number>;
}

export interface DefineManage {
  code: number | null;
  idx: Generated<number>;
  itemName: string | null;
  objName: string;
}

export interface DefineMedal {
  content1: string;
  content2: string;
  eng_name: string;
  idx: number;
  medalCode: number;
  point: Generated<number>;
  regDate: Generated<Date>;
  title: string;
}

export interface DefineQuest {
  content1: string | null;
  content2: string | null;
  content3: string | null;
  content4: string | null;
  idx: Generated<number>;
  progress: string;
  questIDX: number;
  title: string;
}

export interface DefineSiteConfig {
  content: string;
  idx: Generated<number>;
  note: string | null;
  objName: string;
  regDate: Generated<Date>;
}

export interface DefineZipcode {
  bldg: string | null;
  bunji: string | null;
  dong: string | null;
  gugun: string | null;
  ri: string | null;
  seq: string | null;
  sido: string | null;
  zipcode: string | null;
}

export interface EventChuchun {
  accountIDX: number;
  cpID: string | null;
  cpType: Generated<number>;
  flag: Generated<number>;
  friendIDX: number;
  idx: Generated<number>;
  itemFlag: Generated<number>;
  regDate: Generated<Date>;
  userIP: string;
  userType: Generated<number>;
}

export interface EventChuchunConndate {
  accountIDX: number;
  connDate: Date;
}

export interface EventItemLimited {
  AccountIDX: number;
  EventType: number;
  GoodsCount: number;
  GoodsIndex: number;
}

export interface ItemCode {
  idx: Generated<number>;
  itemCode: number | null;
  itemType: number | null;
  itemValue: number | null;
}

export interface LOSAPRIVATEUserInfo {
  email: string | null;
  userID: string | null;
  UserName: string | null;
}

export interface MannerUserID {
  accountIDX: number | null;
  bonus: number | null;
  cnt: number | null;
}

export interface TBLTSWEEKTIME {
  GmtCodeNo: number;
  userID: string;
  Wday: number;
  Wtime: number;
}

export interface TBLTSWEEKTIMEPARENTCHILDINFO {
  Agree_Type: Generated<string | null>;
  AgreeDate: Date | null;
  CHILD_ID: string;
  PARENT_ID: string;
  RegDate: Generated<Date | null>;
  RegIP: string | null;
}

export interface TBWEEKTIME {
  wday: number;
  wtime: number;
}

export interface TEMPMONTHLYMANNERUSER {
  AccountIDX: number | null;
}

export interface UserAbilityDB {
  accountIDX: number;
  class1_basic01: Generated<number>;
  class1_basic02: Generated<number>;
  class1_basic03: Generated<number>;
  class1_basic04: Generated<number>;
  class1_limitdate: Generated<Date>;
  class1_skill1_ad: Generated<number>;
  class1_skill1_as: Generated<number>;
  class1_skill1_asd: Generated<number>;
  class1_skill1_sd: Generated<number>;
  class1_timeslot: Generated<number>;
  class1_type: Generated<number>;
  class2_basic01: Generated<number>;
  class2_basic02: Generated<number>;
  class2_basic03: Generated<number>;
  class2_basic04: Generated<number>;
  class2_limitdate: Generated<Date>;
  class2_skill1_ad: Generated<number>;
  class2_skill1_as: Generated<number>;
  class2_skill1_asd: Generated<number>;
  class2_skill1_sd: Generated<number>;
  class2_timeslot: Generated<number>;
  class2_type: Generated<number>;
  class3_basic01: Generated<number>;
  class3_basic02: Generated<number>;
  class3_basic03: Generated<number>;
  class3_basic04: Generated<number>;
  class3_limitdate: Generated<Date>;
  class3_skill1_ad: Generated<number>;
  class3_skill1_as: Generated<number>;
  class3_skill1_asd: Generated<number>;
  class3_skill1_sd: Generated<number>;
  class3_timeslot: Generated<number>;
  class3_type: Generated<number>;
  class4_basic01: Generated<number>;
  class4_basic02: Generated<number>;
  class4_basic03: Generated<number>;
  class4_basic04: Generated<number>;
  class4_limitdate: Generated<Date>;
  class4_skill1_ad: Generated<number>;
  class4_skill1_as: Generated<number>;
  class4_skill1_asd: Generated<number>;
  class4_skill1_sd: Generated<number>;
  class4_timeslot: Generated<number>;
  class4_type: Generated<number>;
  class5_basic01: Generated<number>;
  class5_basic02: Generated<number>;
  class5_basic03: Generated<number>;
  class5_basic04: Generated<number>;
  class5_limitdate: Generated<Date>;
  class5_skill1_ad: Generated<number>;
  class5_skill1_as: Generated<number>;
  class5_skill1_asd: Generated<number>;
  class5_skill1_sd: Generated<number>;
  class5_timeslot: Generated<number>;
  class5_type: Generated<number>;
  idx: Generated<number>;
  regDate: Generated<Date>;
}

export interface UserAccessoryDB {
  AccountIDX: number;
  ClassType: Generated<number>;
  ComposeCode: Generated<number>;
  ComposeValue: Generated<number>;
  idx: Generated<number>;
  ItemCode: Generated<number>;
  PeriodDate: Generated<Date>;
  PeriodType: Generated<number>;
  RegDate: Generated<Date>;
  StatValue: Generated<number>;
}

export interface UserAttendanceDB {
  accountIDX: number;
  checkDate: Date;
  idx: Generated<number>;
  regDate: Generated<Date>;
}

export interface UserAttendDB {
  AccountIDX: number;
  AttendCount: number;
  ConnectDate: Date;
  RegDate: Date;
  RewardTable: number;
}

export interface UserAwardDB {
  accountIDX: Generated<number>;
  award1_number: Generated<number>;
  award1_point: Generated<number>;
  award1_type: Generated<number>;
  award10_number: Generated<number>;
  award10_point: Generated<number>;
  award10_type: Generated<number>;
  award2_number: Generated<number>;
  award2_point: Generated<number>;
  award2_type: Generated<number>;
  award3_number: Generated<number>;
  award3_point: Generated<number>;
  award3_type: Generated<number>;
  award4_number: Generated<number>;
  award4_point: Generated<number>;
  award4_type: Generated<number>;
  award5_number: Generated<number>;
  award5_point: Generated<number>;
  award5_type: Generated<number>;
  award6_number: Generated<number>;
  award6_point: Generated<number>;
  award6_type: Generated<number>;
  award7_number: Generated<number>;
  award7_point: Generated<number>;
  award7_type: Generated<number>;
  award8_number: Generated<number>;
  award8_point: Generated<number>;
  award8_type: Generated<number>;
  award9_number: Generated<number>;
  award9_point: Generated<number>;
  award9_type: Generated<number>;
  idx: Generated<number>;
  regDate: Generated<Date>;
}

export interface UserCardMatchingDB {
  AccountIDX: number;
  Mark1: Generated<number>;
  Mark2: Generated<number>;
  MissionCount: Generated<number>;
  MissionMark1: Generated<number>;
  MissionMark2: Generated<number>;
  MissionType: Generated<number>;
  RegDate: Date;
  UpdateTime: Date;
}

export interface UserCashDB {
  accountIDX: number;
  amtBonus: Generated<number>;
  amtCash: Generated<number>;
  amtLimit: Generated<number>;
  amtSum: Generated<number>;
  chgDate: Generated<Date>;
  regDate: Generated<Date>;
}

export interface UserCharacterDB {
  accountIDX: number;
  awakeTime: Generated<number>;
  awakeType: Generated<number>;
  CI_beard: Generated<number>;
  CI_face: Generated<number>;
  CI_gender: Generated<number>;
  CI_hair: Generated<number>;
  CI_hairColor: Generated<number>;
  CI_position: Generated<number>;
  CI_skinColor: Generated<number>;
  CI_trinket: Generated<number>;
  CI_type: Generated<number>;
  CI_underwear: Generated<number>;
  ClassType: Generated<number>;
  EI1_type: Generated<number>;
  EI2_type: Generated<number>;
  EI3_type: Generated<number>;
  EI4_type: Generated<number>;
  idx: Generated<number>;
  leaderType: Generated<number>;
  limitTime: Generated<number>;
  limitType: Generated<number>;
  regDate: Generated<Date>;
  rentalTime: Generated<number>;
  rentalType: Generated<number>;
}

export interface UserClassDB {
  accountIDX: number;
  class1_expert: Generated<number>;
  class1_level: Generated<number>;
  class1_stat: Generated<number>;
  class1_type: Generated<number>;
  class10_expert: Generated<number>;
  class10_level: Generated<number>;
  class10_stat: Generated<number>;
  class10_type: Generated<number>;
  class2_expert: Generated<number>;
  class2_level: Generated<number>;
  class2_stat: Generated<number>;
  class2_type: Generated<number>;
  class3_expert: Generated<number>;
  class3_level: Generated<number>;
  class3_stat: Generated<number>;
  class3_type: Generated<number>;
  class4_expert: Generated<number>;
  class4_level: Generated<number>;
  class4_stat: Generated<number>;
  class4_type: Generated<number>;
  class5_expert: Generated<number>;
  class5_level: Generated<number>;
  class5_stat: Generated<number>;
  class5_type: Generated<number>;
  class6_expert: Generated<number>;
  class6_level: Generated<number>;
  class6_stat: Generated<number>;
  class6_type: Generated<number>;
  class7_expert: Generated<number>;
  class7_level: Generated<number>;
  class7_stat: Generated<number>;
  class7_type: Generated<number>;
  class8_expert: Generated<number>;
  class8_level: Generated<number>;
  class8_stat: Generated<number>;
  class8_type: Generated<number>;
  class9_expert: Generated<number>;
  class9_level: Generated<number>;
  class9_stat: Generated<number>;
  class9_type: Generated<number>;
  idx: Generated<number>;
}

export interface UserCloverDB {
  accountIDX: number;
  CloverCnt: Generated<number>;
  LastChargeDate: Generated<number>;
  regDate: Generated<Date>;
  RemainTime: Generated<number>;
}

export interface UserCoinDB {
  AccountIDX: number;
  CoinType: Generated<number>;
  RegDate: Generated<Date>;
  UpdateDate: Date;
}

export interface UserConfigDB {
  accountIDX: number;
  idx: Generated<number>;
  keyvalue: string;
  regDate: Generated<Date>;
}

export interface UserConfigDBTEST {
  accountIDX: number;
  idx: Generated<number>;
  keyvalue: string;
  regDate: Generated<Date>;
}

export interface UserCooperationDB {
  accountIDX: number;
  cpID: string;
  cpIDX: Generated<number | null>;
  cpType: number;
  idx: Generated<number>;
  note: string | null;
  regDate: Generated<Date>;
  userID: string;
}

export interface UserCostumeDB {
  accountIDX: number;
  classType: Generated<number>;
  fcustom: Generated<number>;
  idx: Generated<number>;
  itemCode: Generated<number>;
  mcustom: Generated<number>;
  periodDate: Generated<Date>;
  periodType: Generated<number>;
  regDate: Generated<Date>;
}

export interface UserCustomMedalDB {
  AccountIDX: Generated<number>;
  BasicGrowth1: Generated<number>;
  BasicGrowth2: Generated<number>;
  BasicGrowth3: Generated<number>;
  BasicGrowth4: Generated<number>;
  idx: Generated<number>;
  LimitDate: Generated<Date>;
  LimitType: Generated<number>;
  MedalCode: Generated<number>;
  regDate: Generated<Date>;
  SetCharaterNum: Generated<number>;
  SkillGrowth1: Generated<number>;
  SkillGrowth2: Generated<number>;
  SkillGrowth3: Generated<number>;
  SkillGrowth4: Generated<number>;
}

export interface UserDiceGameDB {
  AccountIDX: number;
  Board: number;
  Position: number;
  RegDate: Date | null;
  RewardStep01: number;
  RewardStep02: number;
  RewardStep03: number;
  RewardStep04: number;
  RewardStep05: number;
  RewardStep06: number;
  RewardStep07: number;
  RewardStep08: number;
  RewardStep09: number;
  RewardStep10: number;
  Trace01: number;
  Trace02: number;
  Trace03: number;
  Trace04: number;
  Trace05: number;
  Trace06: number;
  UpdateTime: Date | null;
}

export interface UserEventBingoNumber {
  accountidx: number;
  number1: number;
  number10: number;
  number11: number;
  number12: number;
  number13: number;
  number14: number;
  number15: number;
  number16: number;
  number17: number;
  number18: number;
  number19: number;
  number2: number;
  number20: number;
  number21: number;
  number22: number;
  number23: number;
  number24: number;
  number25: number;
  number3: number;
  number4: number;
  number5: number;
  number6: number;
  number7: number;
  number8: number;
  number9: number;
  regDate: Date;
}

export interface UserEventBingoPresent {
  accountidx: number;
  item1: number;
  item10: number;
  item11: number;
  item12: number;
  item13: number;
  item2: number;
  item3: number;
  item4: number;
  item5: number;
  item6: number;
  item7: number;
  item8: number;
  item9: number;
  regDate: Date;
}

export interface UserEventDB {
  accountIDX: number;
  eventType: Generated<number>;
  idx: Generated<number>;
  regDate: Generated<Date>;
  value1: Generated<number>;
  value2: Generated<number>;
}

export interface UserEventPirateRouletteNumber {
  accountidx: number;
  HP: number;
  regDate: Date;
  slot1: Generated<number>;
  slot10: Generated<number>;
  slot11: Generated<number>;
  slot12: Generated<number>;
  slot13: Generated<number>;
  slot14: Generated<number>;
  slot15: Generated<number>;
  slot16: Generated<number>;
  slot17: Generated<number>;
  slot18: Generated<number>;
  slot19: Generated<number>;
  slot2: Generated<number>;
  slot20: Generated<number>;
  slot21: Generated<number>;
  slot22: Generated<number>;
  slot23: Generated<number>;
  slot24: Generated<number>;
  slot25: Generated<number>;
  slot26: Generated<number>;
  slot27: Generated<number>;
  slot28: Generated<number>;
  slot29: Generated<number>;
  slot3: Generated<number>;
  slot30: Generated<number>;
  slot31: Generated<number>;
  slot32: Generated<number>;
  slot33: Generated<number>;
  slot34: Generated<number>;
  slot35: Generated<number>;
  slot36: Generated<number>;
  slot37: Generated<number>;
  slot38: Generated<number>;
  slot39: Generated<number>;
  slot4: Generated<number>;
  slot40: Generated<number>;
  slot5: Generated<number>;
  slot6: Generated<number>;
  slot7: Generated<number>;
  slot8: Generated<number>;
  slot9: Generated<number>;
}

export interface UserEventPirateRoulettePresent {
  accountidx: number;
  regDate: Date;
  reward1: Generated<number>;
  reward10: Generated<number>;
  reward11: Generated<number>;
  reward12: Generated<number>;
  reward13: Generated<number>;
  reward14: Generated<number>;
  reward15: Generated<number>;
  reward2: Generated<number>;
  reward3: Generated<number>;
  reward4: Generated<number>;
  reward5: Generated<number>;
  reward6: Generated<number>;
  reward7: Generated<number>;
  reward8: Generated<number>;
  reward9: Generated<number>;
}

export interface UserFishDB {
  accountIDX: number;
  fish1_an: Generated<number>;
  fish1_type: Generated<number>;
  fish10_an: Generated<number>;
  fish10_type: Generated<number>;
  fish11_an: Generated<number>;
  fish11_type: Generated<number>;
  fish12_an: Generated<number>;
  fish12_type: Generated<number>;
  fish13_an: Generated<number>;
  fish13_type: Generated<number>;
  fish14_an: Generated<number>;
  fish14_type: Generated<number>;
  fish15_an: Generated<number>;
  fish15_type: Generated<number>;
  fish16_an: Generated<number>;
  fish16_type: Generated<number>;
  fish17_an: Generated<number>;
  fish17_type: Generated<number>;
  fish18_an: Generated<number>;
  fish18_type: Generated<number>;
  fish19_an: Generated<number>;
  fish19_type: Generated<number>;
  fish2_an: Generated<number>;
  fish2_type: Generated<number>;
  fish20_an: Generated<number>;
  fish20_type: Generated<number>;
  fish3_an: Generated<number>;
  fish3_type: Generated<number>;
  fish4_an: Generated<number>;
  fish4_type: Generated<number>;
  fish5_an: Generated<number>;
  fish5_type: Generated<number>;
  fish6_an: Generated<number>;
  fish6_type: Generated<number>;
  fish7_an: Generated<number>;
  fish7_type: Generated<number>;
  fish8_an: Generated<number>;
  fish8_type: Generated<number>;
  fish9_an: Generated<number>;
  fish9_type: Generated<number>;
  idx: Generated<number>;
  regDate: Generated<Date>;
}

export interface UserFriendBestDB {
  accountIDX: number;
  flag: Generated<number>;
  flagTime: Generated<number>;
  friendIDX: number;
  idx: Generated<number>;
  regDate: Generated<Date>;
}

export interface UserFriendDB {
  flag: Generated<number>;
  friendAccIDX: number;
  idx: Generated<number>;
  receiveBCloverCnt: Generated<number>;
  receiveCloverCnt: Generated<number>;
  receiveCloverDate: Generated<number>;
  regDate: Generated<Date>;
  sendCloverCnt: Generated<number>;
  sendCloverDate: Generated<number>;
  userAccIDX: number;
}

export interface UserFriendListDB {
  friendAccIDX: number;
  guildIDX: number;
  userAccIDX: number;
}

export interface UserFriendListDBTable {
  friendAccIDX: number;
  guildIDX: number;
  userAccIDX: number;
}

export interface UserGameDB {
  accountIDX: number;
  conn_count: Generated<number>;
  connDate: Generated<Date>;
  gameMoney: Generated<number>;
  playTime: Generated<number>;
  Practice: Generated<number>;
  refillData: Generated<number>;
  regDate: Generated<Date>;
  regionType: Generated<number>;
  relateLevel: Generated<number>;
  rencpoint: Generated<number>;
  renspoint: Generated<number>;
  userExcavationEXP: Generated<number>;
  userExcavationLevel: Generated<number>;
  userEXP: Generated<number>;
  userFishingEXP: Generated<number>;
  userFishingLevel: Generated<number>;
  userHerocEXP: Generated<number>;
  userHerosEXP: Generated<number>;
  userLevel: Generated<number>;
  userState: Generated<number>;
}

export interface UserGoldDB {
  AccountIDX: number;
  Amount: Generated<number>;
  ExpirationDate: Generated<Date>;
  GoldStatus: Generated<number>;
  GoldType: Generated<number>;
  idx: Generated<number>;
  OriginalAmount: Generated<number>;
  RegDate: Generated<Date>;
}

export interface UserGuildAttendDB {
  AccountIDX: number;
  GuildIDX: number;
  InitDate: Date;
  RegDate: Date;
}

export interface UserGuildDB {
  aboutguild: string;
  guildLevel: Generated<number>;
  guildmark: number;
  guildName: string;
  idx: Generated<number>;
  maxcount: Generated<number>;
  membercount: Generated<number>;
  point: Generated<number>;
  ranking: Generated<number>;
  regDate: Generated<Date>;
  today_vc: Generated<number>;
  todaypoint: Generated<number>;
  total_vc: Generated<number>;
}

export interface UserGuildHQDB {
  GuildIDX: number;
  ItemCode: number;
  ItemDecoScore: Generated<number>;
  ItemRotate: Generated<number>;
  ItemSerial: Generated<number>;
  ItemStatus: Generated<number>;
  ItemXZ: Generated<number>;
  ItemY: Generated<number>;
}

export interface UserGuildHQVerDB {
  GuildIDX: number;
  RegDate: Generated<Date>;
  UptDate: Generated<Date>;
  VerStatus: Generated<number>;
}

export interface UserGuildInfoDB {
  accountIDX: number;
  AttendDate: Generated<Date>;
  guildIDX: number;
  guildJoinType: Generated<number>;
  guildPosition: string | null;
  GuildRankDate: Generated<Date>;
  idx: Generated<number>;
  msg: Generated<number>;
  regDate: Generated<Date>;
}

export interface UserHqDB {
  accountIDX: number;
  class1_posx: Generated<number>;
  class1_posy: Generated<number>;
  class1_type: Generated<number>;
  class10_posx: Generated<number>;
  class10_posy: Generated<number>;
  class10_type: Generated<number>;
  class2_posx: Generated<number>;
  class2_posy: Generated<number>;
  class2_type: Generated<number>;
  class3_posx: Generated<number>;
  class3_posy: Generated<number>;
  class3_type: Generated<number>;
  class4_posx: Generated<number>;
  class4_posy: Generated<number>;
  class4_type: Generated<number>;
  class5_posx: Generated<number>;
  class5_posy: Generated<number>;
  class5_type: Generated<number>;
  class6_posx: Generated<number>;
  class6_posy: Generated<number>;
  class6_type: Generated<number>;
  class7_posx: Generated<number>;
  class7_posy: Generated<number>;
  class7_type: Generated<number>;
  class8_posx: Generated<number>;
  class8_posy: Generated<number>;
  class8_type: Generated<number>;
  class9_posx: Generated<number>;
  class9_posy: Generated<number>;
  class9_type: Generated<number>;
  idx: Generated<number>;
  lockType: Generated<number>;
  regDate: Generated<Date>;
}

export interface UserInfoBDB {
  accountIDX: number;
  address1: string;
  address2: string;
  mobile: string | null;
  regDate: Generated<Date>;
  tel: string | null;
  zipcode: string;
}

export interface UserInfoDB {
  accountIDX: number;
  checkDate: Date;
  clickDate: Date | null;
  cnnDate: Generated<Date>;
  rec_dec: number;
  rec_inc: number;
  rec_index: number;
  regDate: Generated<Date>;
  userIP: string | null;
  visit_count: number;
}

export interface UserItemDB {
  accountIDX: number;
  idx: Generated<number>;
  item1_code: Generated<number>;
  item1_type: Generated<number>;
  item10_code: Generated<number>;
  item10_type: Generated<number>;
  item11_code: Generated<number>;
  item11_type: Generated<number>;
  item12_code: Generated<number>;
  item12_type: Generated<number>;
  item13_code: Generated<number>;
  item13_type: Generated<number>;
  item14_code: Generated<number>;
  item14_type: Generated<number>;
  item15_code: Generated<number>;
  item15_type: Generated<number>;
  item16_code: Generated<number>;
  item16_type: Generated<number>;
  item17_code: Generated<number>;
  item17_type: Generated<number>;
  item18_code: Generated<number>;
  item18_type: Generated<number>;
  item19_code: Generated<number>;
  item19_type: Generated<number>;
  item2_code: Generated<number>;
  item2_type: Generated<number>;
  item20_code: Generated<number>;
  item20_type: Generated<number>;
  item3_code: Generated<number>;
  item3_type: Generated<number>;
  item4_code: Generated<number>;
  item4_type: Generated<number>;
  item5_code: Generated<number>;
  item5_type: Generated<number>;
  item6_code: Generated<number>;
  item6_type: Generated<number>;
  item7_code: Generated<number>;
  item7_type: Generated<number>;
  item8_code: Generated<number>;
  item8_type: Generated<number>;
  item9_code: Generated<number>;
  item9_type: Generated<number>;
}

export interface UserItemEtcDB {
  accountIDX: number;
  idx: Generated<number>;
  item1_type: Generated<number>;
  item1_value1: Generated<number>;
  item1_value2: Generated<number>;
  item10_type: Generated<number>;
  item10_value1: Generated<number>;
  item10_value2: Generated<number>;
  item11_type: Generated<number>;
  item11_value1: Generated<number>;
  item11_value2: Generated<number>;
  item12_type: Generated<number>;
  item12_value1: Generated<number>;
  item12_value2: Generated<number>;
  item13_type: Generated<number>;
  item13_value1: Generated<number>;
  item13_value2: Generated<number>;
  item14_type: Generated<number>;
  item14_value1: Generated<number>;
  item14_value2: Generated<number>;
  item15_type: Generated<number>;
  item15_value1: Generated<number>;
  item15_value2: Generated<number>;
  item16_type: Generated<number>;
  item16_value1: Generated<number>;
  item16_value2: Generated<number>;
  item17_type: Generated<number>;
  item17_value1: Generated<number>;
  item17_value2: Generated<number>;
  item18_type: Generated<number>;
  item18_value1: Generated<number>;
  item18_value2: Generated<number>;
  item19_type: Generated<number>;
  item19_value1: Generated<number>;
  item19_value2: Generated<number>;
  item2_type: Generated<number>;
  item2_value1: Generated<number>;
  item2_value2: Generated<number>;
  item20_type: Generated<number>;
  item20_value1: Generated<number>;
  item20_value2: Generated<number>;
  item3_type: Generated<number>;
  item3_value1: Generated<number>;
  item3_value2: Generated<number>;
  item4_type: Generated<number>;
  item4_value1: Generated<number>;
  item4_value2: Generated<number>;
  item5_type: Generated<number>;
  item5_value1: Generated<number>;
  item5_value2: Generated<number>;
  item6_type: Generated<number>;
  item6_value1: Generated<number>;
  item6_value2: Generated<number>;
  item7_type: Generated<number>;
  item7_value1: Generated<number>;
  item7_value2: Generated<number>;
  item8_type: Generated<number>;
  item8_value1: Generated<number>;
  item8_value2: Generated<number>;
  item9_type: Generated<number>;
  item9_value1: Generated<number>;
  item9_value2: Generated<number>;
}

export interface UserItemExtraDB {
  accountIDX: number;
  idx: Generated<number>;
  item1_failexp: Generated<number>;
  item1_fcustom: Generated<number>;
  item1_limitDate: Date;
  item1_limitType: Generated<number>;
  item1_mcustom: Generated<number>;
  item1_reinforce: Generated<number>;
  item1_slotindex: Generated<number>;
  item1_tradetype: Generated<number>;
  item1_type: Generated<number>;
  item10_failexp: Generated<number>;
  item10_fcustom: Generated<number>;
  item10_limitDate: Date;
  item10_limitType: Generated<number>;
  item10_mcustom: Generated<number>;
  item10_reinforce: Generated<number>;
  item10_slotindex: Generated<number>;
  item10_tradetype: Generated<number>;
  item10_type: Generated<number>;
  item2_failexp: Generated<number>;
  item2_fcustom: Generated<number>;
  item2_limitDate: Date;
  item2_limitType: Generated<number>;
  item2_mcustom: Generated<number>;
  item2_reinforce: Generated<number>;
  item2_slotindex: Generated<number>;
  item2_tradetype: Generated<number>;
  item2_type: Generated<number>;
  item3_failexp: Generated<number>;
  item3_fcustom: Generated<number>;
  item3_limitDate: Date;
  item3_limitType: Generated<number>;
  item3_mcustom: Generated<number>;
  item3_reinforce: Generated<number>;
  item3_slotindex: Generated<number>;
  item3_tradetype: Generated<number>;
  item3_type: Generated<number>;
  item4_failexp: Generated<number>;
  item4_fcustom: Generated<number>;
  item4_limitDate: Date;
  item4_limitType: Generated<number>;
  item4_mcustom: Generated<number>;
  item4_reinforce: Generated<number>;
  item4_slotindex: Generated<number>;
  item4_tradetype: Generated<number>;
  item4_type: Generated<number>;
  item5_failexp: Generated<number>;
  item5_fcustom: Generated<number>;
  item5_limitDate: Date;
  item5_limitType: Generated<number>;
  item5_mcustom: Generated<number>;
  item5_reinforce: Generated<number>;
  item5_slotindex: Generated<number>;
  item5_tradetype: Generated<number>;
  item5_type: Generated<number>;
  item6_failexp: Generated<number>;
  item6_fcustom: Generated<number>;
  item6_limitDate: Date;
  item6_limitType: Generated<number>;
  item6_mcustom: Generated<number>;
  item6_reinforce: Generated<number>;
  item6_slotindex: Generated<number>;
  item6_tradetype: Generated<number>;
  item6_type: Generated<number>;
  item7_failexp: Generated<number>;
  item7_fcustom: Generated<number>;
  item7_limitDate: Date;
  item7_limitType: Generated<number>;
  item7_mcustom: Generated<number>;
  item7_reinforce: Generated<number>;
  item7_slotindex: Generated<number>;
  item7_tradetype: Generated<number>;
  item7_type: Generated<number>;
  item8_failexp: Generated<number>;
  item8_fcustom: Generated<number>;
  item8_limitDate: Date;
  item8_limitType: Generated<number>;
  item8_mcustom: Generated<number>;
  item8_reinforce: Generated<number>;
  item8_slotindex: Generated<number>;
  item8_tradetype: Generated<number>;
  item8_type: Generated<number>;
  item9_failexp: Generated<number>;
  item9_fcustom: Generated<number>;
  item9_limitDate: Date;
  item9_limitType: Generated<number>;
  item9_mcustom: Generated<number>;
  item9_reinforce: Generated<number>;
  item9_slotindex: Generated<number>;
  item9_tradetype: Generated<number>;
  item9_type: Generated<number>;
  regDate: Generated<Date>;
}

export interface UserItemExtraView {
  accountIDX: number;
  idx: number;
  itemType: number;
  limitDate: Date;
  limitType: number;
  pos: number;
  reinforce: number;
}

export interface UserItemMedalDB {
  accountIDX: number;
  idx: Generated<number>;
  item1_class: Generated<number>;
  item1_limitDate: Date;
  item1_limitType: Generated<number>;
  item1_type: Generated<number>;
  item10_class: Generated<number>;
  item10_limitDate: Date;
  item10_limitType: Generated<number>;
  item10_type: Generated<number>;
  item2_class: Generated<number>;
  item2_limitDate: Date;
  item2_limitType: Generated<number>;
  item2_type: Generated<number>;
  item3_class: Generated<number>;
  item3_limitDate: Date;
  item3_limitType: Generated<number>;
  item3_type: Generated<number>;
  item4_class: Generated<number>;
  item4_limitDate: Date;
  item4_limitType: Generated<number>;
  item4_type: Generated<number>;
  item5_class: Generated<number>;
  item5_limitDate: Date;
  item5_limitType: Generated<number>;
  item5_type: Generated<number>;
  item6_class: Generated<number>;
  item6_limitDate: Date;
  item6_limitType: Generated<number>;
  item6_type: Generated<number>;
  item7_class: Generated<number>;
  item7_limitDate: Date;
  item7_limitType: Generated<number>;
  item7_type: Generated<number>;
  item8_class: Generated<number>;
  item8_limitDate: Date;
  item8_limitType: Generated<number>;
  item8_type: Generated<number>;
  item9_class: Generated<number>;
  item9_limitDate: Date;
  item9_limitType: Generated<number>;
  item9_type: Generated<number>;
  regDate: Generated<Date>;
}

export interface UserItemMedalExtendDB {
  accountIDX: number;
  idx: Generated<number>;
  medal1_class: Generated<number>;
  medal1_period: Generated<number>;
  medal1_slot: Generated<number>;
  medal10_class: Generated<number>;
  medal10_period: Generated<number>;
  medal10_slot: Generated<number>;
  medal2_class: Generated<number>;
  medal2_period: Generated<number>;
  medal2_slot: Generated<number>;
  medal3_class: Generated<number>;
  medal3_period: Generated<number>;
  medal3_slot: Generated<number>;
  medal4_class: Generated<number>;
  medal4_period: Generated<number>;
  medal4_slot: Generated<number>;
  medal5_class: Generated<number>;
  medal5_period: Generated<number>;
  medal5_slot: Generated<number>;
  medal6_class: Generated<number>;
  medal6_period: Generated<number>;
  medal6_slot: Generated<number>;
  medal7_class: Generated<number>;
  medal7_period: Generated<number>;
  medal7_slot: Generated<number>;
  medal8_class: Generated<number>;
  medal8_period: Generated<number>;
  medal8_slot: Generated<number>;
  medal9_class: Generated<number>;
  medal9_period: Generated<number>;
  medal9_slot: Generated<number>;
  regDate: Generated<string>;
}

export interface UserLeagueAuthDB {
  accountIDX: number;
  idx: Generated<number>;
  leagueIDX: number;
  regDate: Generated<Date>;
}

export interface UserLeagueCheerDB {
  accountIDX: number;
  idx: Generated<number>;
  leagueIDX: number;
  regDate: Date;
  teamIDX: number;
}

export interface UserLeagueInfoDB {
  announce: string;
  autoType: Generated<number>;
  bannerA: Generated<number>;
  bannerB: Generated<number>;
  idx: Generated<number>;
  leagueIDX: Generated<number>;
  leagueName: string;
  maxcount: Generated<number>;
  maxRound: number;
  modeType: Generated<number>;
  recruitDate: Generated<number>;
  regDate: Generated<Date>;
  waitDate: Generated<number>;
}

export interface UserLeagueListDB {
  accountIDX: number;
  endDate: number;
  idx: Generated<number>;
  leagueState: Generated<number>;
  leagueType: Generated<number>;
  regDate: Generated<Date>;
  startDate: number;
}

export interface UserLeagueRewardCheerDB {
  accountIDX: number;
  flag: Generated<number>;
  idx: Generated<number>;
  regDate: Date;
  rewardPeso: number;
  startDate: number;
}

export interface UserLeagueRewardDB {
  accountIDX: number;
  currentRound: Generated<number>;
  factionPoint: Generated<number>;
  factionRank: Generated<number>;
  idx: Generated<number>;
  regDate: Generated<Date>;
  rewardPeso: Generated<number>;
  startDate: number;
  userFactionType: Generated<number>;
  winnerFactionType: Generated<number>;
}

export interface UserLeagueRewardUserDB {
  accountIDX: number;
  idx: Generated<number>;
  leagueIDX: Generated<number>;
  leagueName: string;
  maxRound: Generated<number>;
  presentCode1: Generated<number>;
  presentCode2: Generated<number>;
  presentCode3: Generated<number>;
  presentCode4: Generated<number>;
  regDate: Generated<Date>;
  roundnum: Generated<number>;
  sendNickname: string;
}

export interface UserLeagueRoundDB {
  idx: Generated<number>;
  infoIDX: Generated<number>;
  regDate: Generated<Date>;
  roundType1_playDate: Generated<number>;
  roundType1_presentCode1: Generated<number>;
  roundType1_presentCode2: Generated<number>;
  roundType1_presentCode3: Generated<number>;
  roundType1_presentCode4: Generated<number>;
  roundType10_playDate: Generated<number>;
  roundType10_presentCode1: Generated<number>;
  roundType10_presentCode2: Generated<number>;
  roundType10_presentCode3: Generated<number>;
  roundType10_presentCode4: Generated<number>;
  roundType11_playDate: Generated<number>;
  roundType11_presentCode1: Generated<number>;
  roundType11_presentCode2: Generated<number>;
  roundType11_presentCode3: Generated<number>;
  roundType11_presentCode4: Generated<number>;
  roundType2_playDate: Generated<number>;
  roundType2_presentCode1: Generated<number>;
  roundType2_presentCode2: Generated<number>;
  roundType2_presentCode3: Generated<number>;
  roundType2_presentCode4: Generated<number>;
  roundType3_playDate: Generated<number>;
  roundType3_presentCode1: Generated<number>;
  roundType3_presentCode2: Generated<number>;
  roundType3_presentCode3: Generated<number>;
  roundType3_presentCode4: Generated<number>;
  roundType4_playDate: Generated<number>;
  roundType4_presentCode1: Generated<number>;
  roundType4_presentCode2: Generated<number>;
  roundType4_presentCode3: Generated<number>;
  roundType4_presentCode4: Generated<number>;
  roundType5_playDate: Generated<number>;
  roundType5_presentCode1: Generated<number>;
  roundType5_presentCode2: Generated<number>;
  roundType5_presentCode3: Generated<number>;
  roundType5_presentCode4: Generated<number>;
  roundType6_playDate: Generated<number>;
  roundType6_presentCode1: Generated<number>;
  roundType6_presentCode2: Generated<number>;
  roundType6_presentCode3: Generated<number>;
  roundType6_presentCode4: Generated<number>;
  roundType7_playDate: Generated<number>;
  roundType7_presentCode1: Generated<number>;
  roundType7_presentCode2: Generated<number>;
  roundType7_presentCode3: Generated<number>;
  roundType7_presentCode4: Generated<number>;
  roundType8_playDate: Generated<number>;
  roundType8_presentCode1: Generated<number>;
  roundType8_presentCode2: Generated<number>;
  roundType8_presentCode3: Generated<number>;
  roundType8_presentCode4: Generated<number>;
  roundType9_playDate: Generated<number>;
  roundType9_presentCode1: Generated<number>;
  roundType9_presentCode2: Generated<number>;
  roundType9_presentCode3: Generated<number>;
  roundType9_presentCode4: Generated<number>;
}

export interface UserLeagueTeamDB {
  cheerPoint: Generated<number>;
  currentRound: Generated<number>;
  factionPoint: Generated<number>;
  factionType: Generated<number>;
  idx: Generated<number>;
  leaderIDX: number;
  leagueIDX: number;
  leaguePosition: Generated<number>;
  leagueStartPosition: Generated<number>;
  maxcount: Generated<number>;
  regDate: Generated<Date>;
  teamName: string;
}

export interface UserLeagueTeamMemberDB {
  accountIDX: number;
  idx: Generated<number>;
  joinType: Generated<number>;
  leagueIDX: Generated<number>;
  regDate: Generated<Date>;
  teamIDX: Generated<number>;
}

export interface UserLeagueWinnerHistoryDB {
  endDate: number;
  factionName: string | null;
  factionType: number;
  idx: Generated<number>;
  leagueTitle: string;
  regDate: Generated<Date>;
  startDate: number;
  teamIDX: number;
  teamName: string | null;
}

export interface UserLeagueWinnerInfoDB {
  accountIDX: number;
  classFace: Generated<number>;
  classGear1: Generated<number>;
  classGear2: Generated<number>;
  classGear3: Generated<number>;
  classGear4: Generated<number>;
  classGender: Generated<number>;
  classHair: Generated<number>;
  classHairColor: Generated<number>;
  classSkinColor: Generated<number>;
  classType: Generated<number>;
  classUnderwear: Generated<number>;
  historyIDX: Generated<number>;
  idx: Generated<number>;
  nickName: string;
  regDate: Generated<Date>;
  teamIDX: Generated<number>;
  userLevel: number;
}

export interface UserLoginDB {
  accountIDX: number;
  connDate: Generated<Date>;
  encodeKey: Generated<string>;
  gameServerID: Generated<number>;
  userIP: string | null;
}

export interface UserMatchModeDailyRankingDB {
  AccountIDX: number;
  MatchPoint: Generated<number>;
  Ranking: number;
}

export interface UserMatchModeDB {
  AccountIDX: number;
  LoseCount: Generated<number>;
  MatchPoint: number;
  MaxWinCount: Generated<number>;
  PlayCount: Generated<number>;
  RankMMR: Generated<number>;
  RegDate: Generated<Date>;
  WinCount: Generated<number>;
}

export interface UserMatchModeHistoryDB {
  AccountIDX: number;
  idx: Generated<number>;
  OpposingTeamWinCount: Generated<number>;
  PlayDate: Generated<Date>;
  TeamWinCount: Generated<number>;
  WinLoseType: Generated<number>;
}

export interface UserMatchModeSeasonRankingDB {
  AccountIDX: number;
  S1_MatchPoint: Generated<number>;
  S1_Ranking: Generated<number>;
  S1_SeasonDate: Generated<Date>;
  S2_MatchPoint: Generated<number>;
  S2_Ranking: Generated<number>;
  S2_SeasonDate: Generated<Date>;
  S3_MatchPoint: Generated<number>;
  S3_Ranking: Generated<number>;
  S3_SeasonDate: Generated<Date>;
  S4_MatchPoint: Generated<number>;
  S4_Ranking: Generated<number>;
  S4_SeasonDate: Generated<Date>;
  S5_MatchPoint: Generated<number>;
  S5_Ranking: Generated<number>;
  S5_SeasonDate: Generated<Date>;
  S6_MatchPoint: Generated<number>;
  S6_Ranking: Generated<number>;
  S6_SeasonDate: Generated<Date>;
  S7_MatchPoint: Generated<number>;
  S7_Ranking: Generated<number>;
  S7_SeasonDate: Generated<Date>;
}

export interface UserMedalDB {
  accountIDX: number;
  idx: Generated<number>;
  medal1_type: Generated<number>;
  medal10_type: Generated<number>;
  medal2_type: Generated<number>;
  medal3_type: Generated<number>;
  medal4_type: Generated<number>;
  medal5_type: Generated<number>;
  medal6_type: Generated<number>;
  medal7_type: Generated<number>;
  medal8_type: Generated<number>;
  medal9_type: Generated<number>;
  regDate: Generated<Date>;
}

export interface UserMedalDBReceive {
  accountIDX: number;
  flag: Generated<number>;
  idx: Generated<number>;
  medalIDX: number;
  regDate: Generated<Date>;
}

export interface UserMemberDB {
  accountIDX: Generated<number>;
  cpType: Generated<number>;
  email: string;
  eventType: Generated<number>;
  joinType: Generated<number>;
  limitDate: Generated<Date>;
  limitType: Generated<number>;
  mailling: number;
  makeType: Generated<number>;
  nickName: string;
  regDate: Generated<Date>;
  trackingcode: Generated<number>;
  userID: string;
  userPWD: string;
  userType: Generated<number>;
}

export interface UserMissionDB {
  AccountIDX: number;
  MissionCode: number;
  MissionStatus: Generated<number>;
  MissionType: number;
  MissionValue: number;
  RegDate: Generated<Date>;
}

export interface UserNameDB {
  accountIDX: number;
  certType: Generated<string>;
  ipinCI: string | null;
  ipinDI: string | null;
  realType: Generated<number>;
  regDate: Generated<Date>;
  returnValue: number;
  userBirthday: string;
  userEnCode: string;
  userGender: number;
  userIP: string | null;
  userJumin1: string | null;
  userJumin2: string | null;
  userName: string;
  userNumber: number;
  virtualJumin: string | null;
}

export interface UserOakBarrelDB {
  AccountIDX: number;
  LimitSword: Generated<number>;
  RegDate: Generated<Date>;
  Slot1: Generated<number>;
  Slot10: Generated<number>;
  Slot11: Generated<number>;
  Slot12: Generated<number>;
  Slot2: Generated<number>;
  Slot3: Generated<number>;
  Slot4: Generated<number>;
  Slot5: Generated<number>;
  Slot6: Generated<number>;
  Slot7: Generated<number>;
  Slot8: Generated<number>;
  Slot9: Generated<number>;
  Step: Generated<number>;
  UpdateTime: Generated<Date>;
}

export interface UserParentDB {
  accountIDX: number;
  agreeEDate: Date | null;
  agreeSDate: Date | null;
  agreeType: Generated<number>;
  Certify_Type: Generated<string | null>;
  email: string | null;
  logIDX: Generated<number>;
  parentBirth: string | null;
  parentEncode: string | null;
  parentJumin1: string | null;
  parentJumin2: string | null;
  parentName: string;
  parentNumber: number | null;
  PIpinCI: string | null;
  PIpinDI: string | null;
  regDate: Generated<Date>;
}

export interface UserPCBangPlayTimeDB {
  AccountIDX: Generated<number>;
  PCBangDate: Generated<string>;
  PCBangIndex: Generated<number>;
  PCBangPlayTime: Generated<number>;
}

export interface UserPCBangPregentDB {
  AccountIDX: Generated<number>;
  PCBangBonusCash: Generated<number>;
  PCBangCount: Generated<number>;
  PCBangDate: Generated<string>;
}

export interface UserPersonalHQDB {
  AccountIDX: number;
  ItemCode: number;
  ItemDecoScore: Generated<number>;
  ItemRotate: Generated<number>;
  ItemSerial: Generated<number>;
  ItemStatus: Generated<number>;
  ItemXZ: Generated<number>;
  ItemY: Generated<number>;
}

export interface UserPetDB {
  accountIDX: number;
  petCode: Generated<number>;
  petEquip: Generated<number>;
  petExp: Generated<number>;
  petIDX: Generated<number>;
  petLevel: Generated<number>;
  petRank: Generated<number>;
  petStatus: Generated<number>;
  regDate: Generated<Date>;
}

export interface UserPieceDB {
  accountIDX: number;
  idx: Generated<number>;
  piece1_cnt: Generated<number>;
  piece1_type: Generated<number>;
  piece1_value1: Generated<number>;
  piece1_value2: Generated<number>;
  piece10_cnt: Generated<number>;
  piece10_type: Generated<number>;
  piece10_value1: Generated<number>;
  piece10_value2: Generated<number>;
  piece2_cnt: Generated<number>;
  piece2_type: Generated<number>;
  piece2_value1: Generated<number>;
  piece2_value2: Generated<number>;
  piece3_cnt: Generated<number>;
  piece3_type: Generated<number>;
  piece3_value1: Generated<number>;
  piece3_value2: Generated<number>;
  piece4_cnt: Generated<number>;
  piece4_type: Generated<number>;
  piece4_value1: Generated<number>;
  piece4_value2: Generated<number>;
  piece5_cnt: Generated<number>;
  piece5_type: Generated<number>;
  piece5_value1: Generated<number>;
  piece5_value2: Generated<number>;
  piece6_cnt: Generated<number>;
  piece6_type: Generated<number>;
  piece6_value1: Generated<number>;
  piece6_value2: Generated<number>;
  piece7_cnt: Generated<number>;
  piece7_type: Generated<number>;
  piece7_value1: Generated<number>;
  piece7_value2: Generated<number>;
  piece8_cnt: Generated<number>;
  piece8_type: Generated<number>;
  piece8_value1: Generated<number>;
  piece8_value2: Generated<number>;
  piece9_cnt: Generated<number>;
  piece9_type: Generated<number>;
  piece9_value1: Generated<number>;
  piece9_value2: Generated<number>;
  regDate: Generated<Date>;
}

export interface UserPopStoreDB {
  AccountIDX: number;
  PopupSlot: number;
  RegDate: Generated<Date>;
}

export interface UserPracticeDB {
  AccountIDX: number;
  PracticeCount: Generated<number>;
  PracticeGrade: Generated<number>;
  PracticeIDX: Generated<number>;
  PracticeRank: Generated<number>;
  PracticeTime: Generated<number>;
  regDate: Generated<Date>;
  UpdateDate: Generated<Date>;
}

export interface UserPracticeDBPresent {
  Code1: number;
  Code2: number;
  Code3: number;
  Code4: number;
  Code5: number;
  PresentType1: number;
  PresentType2: number;
  PresentType3: number;
  PresentType4: number;
  PresentType5: number;
  PresentValue: number;
  Value1: number;
  Value2: number;
  Value3: number;
  Value4: number;
  Value5: number;
}

export interface UserPracticeDBRanking {
  AccountIDX: number;
  EndDate: string;
  limitDate: Date | null;
  msgType: number | null;
  PracticeIDX: Generated<number>;
  PracticeRank: Generated<number>;
  sendIDX: number;
  StartDate: string;
  value: number;
}

export interface UserPresentDB {
  flag: number;
  idx: Generated<number>;
  limitDate: Date;
  msgType: number;
  presentType: Generated<number>;
  receiveIDX: number;
  regDate: Generated<Date>;
  sendIDX: number;
  TranIDX: Generated<number>;
  value1: Generated<number>;
  value2: Generated<number>;
  value3: Generated<number>;
  value4: Generated<number>;
}

export interface UserQuestCompleteDB {
  accountIDX: number;
  idx: Generated<number>;
  quest1_time: Generated<number>;
  quest1_type: Generated<number>;
  quest10_time: Generated<number>;
  quest10_type: Generated<number>;
  quest11_time: Generated<number>;
  quest11_type: Generated<number>;
  quest12_time: Generated<number>;
  quest12_type: Generated<number>;
  quest13_time: Generated<number>;
  quest13_type: Generated<number>;
  quest14_time: Generated<number>;
  quest14_type: Generated<number>;
  quest15_time: Generated<number>;
  quest15_type: Generated<number>;
  quest16_time: Generated<number>;
  quest16_type: Generated<number>;
  quest17_time: Generated<number>;
  quest17_type: Generated<number>;
  quest18_time: Generated<number>;
  quest18_type: Generated<number>;
  quest19_time: Generated<number>;
  quest19_type: Generated<number>;
  quest2_time: Generated<number>;
  quest2_type: Generated<number>;
  quest20_time: Generated<number>;
  quest20_type: Generated<number>;
  quest3_time: Generated<number>;
  quest3_type: Generated<number>;
  quest4_time: Generated<number>;
  quest4_type: Generated<number>;
  quest5_time: Generated<number>;
  quest5_type: Generated<number>;
  quest6_time: Generated<number>;
  quest6_type: Generated<number>;
  quest7_time: Generated<number>;
  quest7_type: Generated<number>;
  quest8_time: Generated<number>;
  quest8_type: Generated<number>;
  quest9_time: Generated<number>;
  quest9_type: Generated<number>;
  regDate: Generated<Date>;
}

export interface UserQuestCompleteView {
  accountIDX: number;
  idx: number;
  pos: number;
  quest_time: number;
  quest_type: number;
}

export interface UserQuestDB {
  accountIDX: number;
  idx: Generated<number>;
  quest1_time: Generated<number>;
  quest1_type: Generated<number>;
  quest1_value1: Generated<number>;
  quest1_value2: Generated<number>;
  quest10_time: Generated<number>;
  quest10_type: Generated<number>;
  quest10_value1: Generated<number>;
  quest10_value2: Generated<number>;
  quest11_time: Generated<number>;
  quest11_type: Generated<number>;
  quest11_value1: Generated<number>;
  quest11_value2: Generated<number>;
  quest12_time: Generated<number>;
  quest12_type: Generated<number>;
  quest12_value1: Generated<number>;
  quest12_value2: Generated<number>;
  quest13_time: Generated<number>;
  quest13_type: Generated<number>;
  quest13_value1: Generated<number>;
  quest13_value2: Generated<number>;
  quest14_time: Generated<number>;
  quest14_type: Generated<number>;
  quest14_value1: Generated<number>;
  quest14_value2: Generated<number>;
  quest15_time: Generated<number>;
  quest15_type: Generated<number>;
  quest15_value1: Generated<number>;
  quest15_value2: Generated<number>;
  quest16_time: Generated<number>;
  quest16_type: Generated<number>;
  quest16_value1: Generated<number>;
  quest16_value2: Generated<number>;
  quest17_time: Generated<number>;
  quest17_type: Generated<number>;
  quest17_value1: Generated<number>;
  quest17_value2: Generated<number>;
  quest18_time: Generated<number>;
  quest18_type: Generated<number>;
  quest18_value1: Generated<number>;
  quest18_value2: Generated<number>;
  quest19_time: Generated<number>;
  quest19_type: Generated<number>;
  quest19_value1: Generated<number>;
  quest19_value2: Generated<number>;
  quest2_time: Generated<number>;
  quest2_type: Generated<number>;
  quest2_value1: Generated<number>;
  quest2_value2: Generated<number>;
  quest20_time: Generated<number>;
  quest20_type: Generated<number>;
  quest20_value1: Generated<number>;
  quest20_value2: Generated<number>;
  quest3_time: Generated<number>;
  quest3_type: Generated<number>;
  quest3_value1: Generated<number>;
  quest3_value2: Generated<number>;
  quest4_time: Generated<number>;
  quest4_type: Generated<number>;
  quest4_value1: Generated<number>;
  quest4_value2: Generated<number>;
  quest5_time: Generated<number>;
  quest5_type: Generated<number>;
  quest5_value1: Generated<number>;
  quest5_value2: Generated<number>;
  quest6_time: Generated<number>;
  quest6_type: Generated<number>;
  quest6_value1: Generated<number>;
  quest6_value2: Generated<number>;
  quest7_time: Generated<number>;
  quest7_type: Generated<number>;
  quest7_value1: Generated<number>;
  quest7_value2: Generated<number>;
  quest8_time: Generated<number>;
  quest8_type: Generated<number>;
  quest8_value1: Generated<number>;
  quest8_value2: Generated<number>;
  quest9_time: Generated<number>;
  quest9_type: Generated<number>;
  quest9_value1: Generated<number>;
  quest9_value2: Generated<number>;
  regDate: Generated<Date>;
}

export interface UserQuestView {
  accountIDX: number;
  idx: number;
  pos: number;
  quest_time: number;
  quest_type: number;
  quest_value1: number;
  quest_value2: number;
}

export interface UserRankingDB {
  accountIDX: number;
  award: Generated<number>;
  battle: Generated<number>;
  class: Generated<number>;
  medal: Generated<number>;
  regDate: Generated<Date>;
  region: Generated<number>;
  tester: Generated<number>;
  training: Generated<number>;
}

export interface UserRankingDBAward {
  accountIDX: number;
  award1_now: Generated<number>;
  award1_point: Generated<number>;
  award1_prev: Generated<number>;
  award10_now: Generated<number>;
  award10_point: Generated<number>;
  award10_prev: Generated<number>;
  award11_now: Generated<number>;
  award11_point: Generated<number>;
  award11_prev: Generated<number>;
  award12_now: Generated<number>;
  award12_point: Generated<number>;
  award12_prev: Generated<number>;
  award13_now: Generated<number>;
  award13_point: Generated<number>;
  award13_prev: Generated<number>;
  award14_now: Generated<number>;
  award14_point: Generated<number>;
  award14_prev: Generated<number>;
  award15_now: Generated<number>;
  award15_point: Generated<number>;
  award15_prev: Generated<number>;
  award16_now: Generated<number>;
  award16_point: Generated<number>;
  award16_prev: Generated<number>;
  award17_now: Generated<number>;
  award17_point: Generated<number>;
  award17_prev: Generated<number>;
  award18_now: Generated<number>;
  award18_point: Generated<number>;
  award18_prev: Generated<number>;
  award19_now: Generated<number>;
  award19_point: Generated<number>;
  award19_prev: Generated<number>;
  award2_now: Generated<number>;
  award2_point: Generated<number>;
  award2_prev: Generated<number>;
  award20_now: Generated<number>;
  award20_point: Generated<number>;
  award20_prev: Generated<number>;
  award21_now: Generated<number>;
  award21_point: Generated<number>;
  award21_prev: Generated<number>;
  award22_now: Generated<number>;
  award22_point: Generated<number>;
  award22_prev: Generated<number>;
  award23_now: Generated<number>;
  award23_point: Generated<number>;
  award23_prev: Generated<number>;
  award24_now: Generated<number>;
  award24_point: Generated<number>;
  award24_prev: Generated<number>;
  award25_now: Generated<number>;
  award25_point: Generated<number>;
  award25_prev: Generated<number>;
  award26_now: Generated<number>;
  award26_point: Generated<number>;
  award26_prev: Generated<number>;
  award27_now: Generated<number>;
  award27_point: Generated<number>;
  award27_prev: Generated<number>;
  award3_now: Generated<number>;
  award3_point: Generated<number>;
  award3_prev: Generated<number>;
  award4_now: Generated<number>;
  award4_point: Generated<number>;
  award4_prev: Generated<number>;
  award5_now: Generated<number>;
  award5_point: Generated<number>;
  award5_prev: Generated<number>;
  award6_now: Generated<number>;
  award6_point: Generated<number>;
  award6_prev: Generated<number>;
  award7_now: Generated<number>;
  award7_point: Generated<number>;
  award7_prev: Generated<number>;
  award8_now: Generated<number>;
  award8_point: Generated<number>;
  award8_prev: Generated<number>;
  award9_now: Generated<number>;
  award9_point: Generated<number>;
  award9_prev: Generated<number>;
  awardLevel: Generated<number>;
  expert: Generated<number>;
  regDate: Generated<Date>;
}

export interface UserRankingDBAwardTop100 {
  accountIDX: number;
  awardEXP: Generated<number>;
  awardType: Generated<number>;
  guildIDX: number | null;
  idx: Generated<number>;
  nickName: string | null;
  rank_now: Generated<number>;
  rank_prev: Generated<number>;
  userLevel: number | null;
}

export interface UserRankingDBAwardTop3 {
  awardType: number;
  dateIDX: string;
  idx: Generated<number>;
  rank1_accountIDX: number;
  rank1_nickName: string;
  rank1_userLevel: number;
  rank2_accountIDX: number;
  rank2_nickName: string;
  rank2_userLevel: number;
  rank3_accountIDX: number;
  rank3_nickName: string;
  rank3_userLevel: number;
}

export interface UserRankingDBBattle {
  accountIDX: number;
  lose_fix: Generated<number>;
  lose_prev: Generated<number>;
  rank_battle: Generated<number>;
  rank_now: Generated<number>;
  rank_prev: Generated<number>;
  rank_total: Generated<number>;
  regDate: Generated<Date>;
  tie_fix: Generated<number>;
  tie_prev: Generated<number>;
  win_fix: Generated<number>;
  win_prev: Generated<number>;
}

export interface UserRankingDBClass {
  accountIDX: number | null;
  classType: number | null;
  expert: number | null;
  nowRanking: number | null;
  prevRanking: number | null;
  userLevel: number | null;
}

export interface UserRankingDBClassgroup {
  accountIDX: number;
  expert: Generated<number>;
  nickName: string | null;
  ranking_1day: Generated<number>;
  ranking_2day: Generated<number>;
  ranking_3day: Generated<number>;
  ranking_4day: Generated<number>;
  ranking_5day: Generated<number>;
  ranking_6day: Generated<number>;
  ranking_7day: Generated<number>;
  ranking_8day: Generated<number>;
  regDate: Generated<Date>;
  userLevel: Generated<number>;
}

export interface UserRankingDBClassgroupTop10000 {
  accountIDX: number;
  expert: number;
  guildIDX: number | null;
  guildMark: number | null;
  guildName: string | null;
  idx: Generated<number>;
  nickName: string | null;
  rank_now: number;
  rank_prev: number;
  regDate: Date;
  userLevel: number;
}

export interface UserRankingDBClassTop100 {
  accountIDX: number;
  classEXP: Generated<number>;
  classLevel: Generated<number>;
  classType: Generated<number>;
  guildIDX: number | null;
  idx: Generated<number>;
  nickName: string | null;
  rank_now: Generated<number>;
  rank_prev: Generated<number>;
  userLevel: number | null;
}

export interface UserRankingDBClassTop3 {
  classType: number;
  dateIDX: string;
  idx: Generated<number>;
  rank1_accountIDX: number;
  rank1_nickName: string;
  rank1_userLevel: number;
  rank2_accountIDX: number;
  rank2_nickName: string;
  rank2_userLevel: number;
  rank3_accountIDX: number;
  rank3_nickName: string;
  rank3_userLevel: number;
}

export interface UserRankingDBFaction {
  accountIDX: number;
  lose_fix: Generated<number>;
  lose_prev: Generated<number>;
  rank_faction: Generated<number>;
  rank_now: Generated<number>;
  rank_prev: Generated<number>;
  rank_total: Generated<number>;
  regDate: Generated<Date>;
  tie_fix: Generated<number>;
  tie_prev: Generated<number>;
  win_fix: Generated<number>;
  win_prev: Generated<number>;
}

export interface UserRankingDBHero {
  accountIDX: number;
  daily: Generated<number>;
  dailyB: Generated<number>;
  idx: Generated<number>;
  regDate: Generated<Date>;
  season1: Generated<number>;
  season2: Generated<number>;
  season3: Generated<number>;
  season4: Generated<number>;
  season5: Generated<number>;
  season6: Generated<number>;
  title: Generated<number>;
}

export interface UserRankingDBMedal {
  accountIDX: number;
  expert: Generated<number>;
  medalLevel: Generated<number>;
  ranking_now: Generated<number>;
  ranking_prev: Generated<number>;
  regDate: Generated<Date>;
}

export interface UserRankingDBTemp {
  accountIDX: number;
  rank: number | null;
}

export interface UserRankingDBTempExpert {
  accountIDX: number;
  expert: number;
}

export interface UserRankingDBTempLevel {
  accountIDX: number;
  expert: number;
  level: number;
}

export interface UserRankingDBTempRanking {
  accountIDX: number;
  idx: Generated<number>;
}

export interface UserRecordBattleDB {
  accountIDX: number;
  regDate: Generated<Date>;
  type1_death: Generated<number>;
  type1_kill: Generated<number>;
  type1_lose: Generated<number>;
  type1_win: Generated<number>;
  type2_death: Generated<number>;
  type2_kill: Generated<number>;
  type2_lose: Generated<number>;
  type2_win: Generated<number>;
  type3_death: Generated<number>;
  type3_kill: Generated<number>;
  type3_lose: Generated<number>;
  type3_win: Generated<number>;
  type4_death: Generated<number>;
  type4_kill: Generated<number>;
  type4_lose: Generated<number>;
  type4_win: Generated<number>;
}

export interface UserRecordGuildDB {
  guildIDX: number;
  regDate: Generated<Date>;
  type1_death: Generated<number>;
  type1_kill: Generated<number>;
  type1_lose: Generated<number>;
  type1_win: Generated<number>;
}

export interface UserRegionDB {
  idx: Generated<number>;
  regDate: Generated<Date>;
  rt1point: Generated<number>;
  rt1point_bonus: Generated<number>;
  rt1point_today: Generated<number>;
  rt2point: Generated<number>;
  rt2point_bonus: Generated<number>;
  rt2point_today: Generated<number>;
}

export interface UserRegionDBCompen {
  accountIDX: number;
  idx: Generated<number>;
  regDate: Generated<Date>;
  regionRanking: Generated<number>;
  regionType: Generated<number>;
  renspoint: Generated<number>;
  rt1count: Generated<number>;
  rt1point: Generated<number>;
  rt1point_bonus: Generated<number>;
  rt2count: Generated<number>;
  rt2point: Generated<number>;
  rt2point_bonus: Generated<number>;
}

export interface UserRegionDBHistory {
  idx: Generated<number>;
  membercount: Generated<number>;
  point: Generated<number>;
  point_bonus: Generated<number>;
  regDate: Generated<Date>;
  regionType: Generated<number>;
  season: Generated<number>;
}

export interface UserRelativeLevelDB {
  accountIDX: number;
  init_time: Generated<number>;
  regDate: Date;
  reward_State: Generated<number>;
  weekend_BackupExp: Generated<number>;
  weekend_BackupLevel: Generated<number>;
}

export interface UserSBoxDB {
  accountIDX: number;
  amount: Generated<number>;
  billingID: string;
  bonusAmount: Generated<number>;
  flag: Generated<number>;
  idx: Generated<number>;
  limitDate: Date;
  presentType: Generated<number>;
  regDate: Generated<Date>;
  value1: Generated<number>;
  value2: Generated<number>;
}

export interface UserSpentGoldDB {
  AccountIDX: number;
  RegDate: Generated<Date>;
  UserSpentGold: number;
}

export interface UserSpentGoldLogDB {
  AccountIDX: number;
  RegDate: Date;
  UserSpentGold: number;
}

export interface UserSpiritDB {
  AccountIDX: number;
  idx: Generated<number>;
  RegDate: Generated<Date>;
  SpiritCount: Generated<number>;
  SpiritType: Generated<number>;
}

export interface UserTimeCashDB {
  AccountIDX: number;
  ItemCode: number;
  ItemCount: Generated<number>;
  ItemStatus: Generated<number>;
  OverDate: Date;
  RegDate: Date;
  StartDate: Date;
  UpdDate: Date;
}

export interface UserTimeGateDB {
  AccountIDX: number;
  GetTime: Generated<Date>;
}

export interface UserTitleDB {
  AccountIDX: number;
  RegDate: Generated<Date>;
  TitleCode: number;
  TitleEquip: Generated<number>;
  TitleLevel: Generated<number>;
  TitlePremium: Generated<number>;
  TitleStatus: Generated<number>;
  TitleValue: number;
  UpdDate: Generated<Date>;
}

export interface UserTradeDB {
  accountIDX: number;
  fcustom: Generated<number>;
  idx: Generated<number>;
  itemType: Generated<number>;
  mcustom: Generated<number>;
  periodDate: Generated<number>;
  price: Generated<number>;
  regDate: Generated<Date>;
  userIP: string | null;
  value1: Generated<number>;
  value2: Generated<number>;
}

export interface LosaGame {
  classPriceView: ClassPriceView;
  define_award: DefineAward;
  define_blockIP: DefineBlockIP;
  define_class: DefineClass;
  define_class_price: DefineClassPrice;
  define_config: DefineConfig;
  define_encode_key: DefineEncodeKey;
  define_game_server: DefineGameServer;
  define_gear_customidx: DefineGearCustomidx;
  define_geoip: DefineGeoip;
  define_hero_price: DefineHeroPrice;
  define_manage: DefineManage;
  define_medal: DefineMedal;
  define_quest: DefineQuest;
  define_site_config: DefineSiteConfig;
  define_zipcode: DefineZipcode;
  event_chuchun: EventChuchun;
  event_chuchun_conndate: EventChuchunConndate;
  event_item_limited: EventItemLimited;
  itemCode: ItemCode;
  LOSA_PRIVATE_UserInfo: LOSAPRIVATEUserInfo;
  mannerUserID: MannerUserID;
  TB_LTS_WEEKTIME: TBLTSWEEKTIME;
  TB_LTS_WEEKTIME_PARENT_CHILD_INFO: TBLTSWEEKTIMEPARENTCHILDINFO;
  TB_WEEKTIME: TBWEEKTIME;
  TEMP_MONTHLY_MANNER_USER: TEMPMONTHLYMANNERUSER;
  userAbilityDB: UserAbilityDB;
  userAccessoryDB: UserAccessoryDB;
  userAttendanceDB: UserAttendanceDB;
  userAttendDB: UserAttendDB;
  userAwardDB: UserAwardDB;
  userCardMatchingDB: UserCardMatchingDB;
  userCashDB: UserCashDB;
  userCharacterDB: UserCharacterDB;
  userClassDB: UserClassDB;
  userCloverDB: UserCloverDB;
  userCoinDB: UserCoinDB;
  userConfigDB: UserConfigDB;
  userConfigDB_TEST: UserConfigDBTEST;
  userCooperationDB: UserCooperationDB;
  userCostumeDB: UserCostumeDB;
  userCustomMedalDB: UserCustomMedalDB;
  userDiceGameDB: UserDiceGameDB;
  userEventBingo_Number: UserEventBingoNumber;
  userEventBingo_Present: UserEventBingoPresent;
  userEventDB: UserEventDB;
  userEventPirateRoulette_Number: UserEventPirateRouletteNumber;
  userEventPirateRoulette_Present: UserEventPirateRoulettePresent;
  userFishDB: UserFishDB;
  userFriendBestDB: UserFriendBestDB;
  userFriendDB: UserFriendDB;
  userFriendListDB: UserFriendListDB;
  userFriendListDB_table: UserFriendListDBTable;
  userGameDB: UserGameDB;
  userGoldDB: UserGoldDB;
  userGuildAttendDB: UserGuildAttendDB;
  userGuildDB: UserGuildDB;
  userGuildHQDB: UserGuildHQDB;
  userGuildHQVerDB: UserGuildHQVerDB;
  userGuildInfoDB: UserGuildInfoDB;
  userHqDB: UserHqDB;
  userInfoBDB: UserInfoBDB;
  userInfoDB: UserInfoDB;
  userItemDB: UserItemDB;
  userItemEtcDB: UserItemEtcDB;
  userItemExtraDB: UserItemExtraDB;
  userItemExtraView: UserItemExtraView;
  userItemMedalDB: UserItemMedalDB;
  userItemMedalExtendDB: UserItemMedalExtendDB;
  userLeagueAuthDB: UserLeagueAuthDB;
  userLeagueCheerDB: UserLeagueCheerDB;
  userLeagueInfoDB: UserLeagueInfoDB;
  userLeagueListDB: UserLeagueListDB;
  userLeagueRewardCheerDB: UserLeagueRewardCheerDB;
  userLeagueRewardDB: UserLeagueRewardDB;
  userLeagueRewardUserDB: UserLeagueRewardUserDB;
  userLeagueRoundDB: UserLeagueRoundDB;
  userLeagueTeamDB: UserLeagueTeamDB;
  userLeagueTeamMemberDB: UserLeagueTeamMemberDB;
  userLeagueWinnerHistoryDB: UserLeagueWinnerHistoryDB;
  userLeagueWinnerInfoDB: UserLeagueWinnerInfoDB;
  userLoginDB: UserLoginDB;
  userMatchModeDailyRankingDB: UserMatchModeDailyRankingDB;
  userMatchModeDB: UserMatchModeDB;
  userMatchModeHistoryDB: UserMatchModeHistoryDB;
  userMatchModeSeasonRankingDB: UserMatchModeSeasonRankingDB;
  userMedalDB: UserMedalDB;
  userMedalDB_receive: UserMedalDBReceive;
  userMemberDB: UserMemberDB;
  userMissionDB: UserMissionDB;
  userNameDB: UserNameDB;
  userOakBarrelDB: UserOakBarrelDB;
  userParentDB: UserParentDB;
  userPCBangPlayTimeDB: UserPCBangPlayTimeDB;
  userPCBangPregentDB: UserPCBangPregentDB;
  userPersonalHQDB: UserPersonalHQDB;
  userPetDB: UserPetDB;
  userPieceDB: UserPieceDB;
  userPopStoreDB: UserPopStoreDB;
  userPracticeDB: UserPracticeDB;
  userPracticeDB_Present: UserPracticeDBPresent;
  userPracticeDB_Ranking: UserPracticeDBRanking;
  userPresentDB: UserPresentDB;
  userQuestCompleteDB: UserQuestCompleteDB;
  userQuestCompleteView: UserQuestCompleteView;
  userQuestDB: UserQuestDB;
  userQuestView: UserQuestView;
  userRankingDB: UserRankingDB;
  userRankingDB_award: UserRankingDBAward;
  userRankingDB_award_top100: UserRankingDBAwardTop100;
  userRankingDB_award_top3: UserRankingDBAwardTop3;
  userRankingDB_battle: UserRankingDBBattle;
  userRankingDB_class: UserRankingDBClass;
  userRankingDB_class_top100: UserRankingDBClassTop100;
  userRankingDB_class_top3: UserRankingDBClassTop3;
  userRankingDB_classgroup: UserRankingDBClassgroup;
  userRankingDB_classgroup_top10000: UserRankingDBClassgroupTop10000;
  userRankingDB_faction: UserRankingDBFaction;
  userRankingDB_hero: UserRankingDBHero;
  userRankingDB_medal: UserRankingDBMedal;
  userRankingDB_temp: UserRankingDBTemp;
  userRankingDB_temp_expert: UserRankingDBTempExpert;
  userRankingDB_temp_level: UserRankingDBTempLevel;
  userRankingDB_temp_ranking: UserRankingDBTempRanking;
  userRecordBattleDB: UserRecordBattleDB;
  userRecordGuildDB: UserRecordGuildDB;
  userRegionDB: UserRegionDB;
  userRegionDB_compen: UserRegionDBCompen;
  userRegionDB_history: UserRegionDBHistory;
  userRelativeLevelDB: UserRelativeLevelDB;
  userSBoxDB: UserSBoxDB;
  userSpentGoldDB: UserSpentGoldDB;
  userSpentGoldLogDB: UserSpentGoldLogDB;
  userSpiritDB: UserSpiritDB;
  userTimeCashDB: UserTimeCashDB;
  userTimeGateDB: UserTimeGateDB;
  userTitleDB: UserTitleDB;
  userTradeDB: UserTradeDB;
}
